// ============================================================
// spots.ts — Fishing hotspot definitions for Brevard County, FL
// ============================================================

import type { FishingSpot } from './types';

/**
 * Static array of 14 fishing hotspots across Brevard County, FL.
 *
 * Each entry describes a location's species targets, tide preference,
 * habitat features, and locally-sourced fishing tips. This data is used by
 * `FishingEngine.rateSpot()` to score conditions and by `AppContext` to
 * derive scored markers for the map.
 */
export const FISHING_SPOTS: FishingSpot[] = [
    {
        id: 'mosquito-lagoon',
        name: 'Mosquito Lagoon',
        lat: 28.720,
        lng: -80.830,
        species: ['redfish', 'snook'],
        description: 'One of the most celebrated sight-fishing destinations in the world. Crystal-clear, ultra-shallow grass flats hold world-class redfish year-round. Strict no-wake zones preserve pristine conditions.',
        features: ['flats', 'grass', 'shallow', 'sight-fishing'],
        tidePreference: 'incoming',
        tips: [
            'Best on incoming tide with 12–18 inches of water over the grass',
            'Sight-cast to tailing or pushing reds in low-light hours',
            'Gold Johnson spoons, DOA Shrimp, and live crabs dominate',
            'Dawn patrol before other boats disturb the flats is essential',
            'Polarized sunglasses are a must for spotting fish',
        ],
    },
    {
        id: 'haulover-canal',
        name: 'Haulover Canal',
        lat: 28.6394,
        lng: -80.7853,
        species: ['redfish', 'snook', 'tarpon'],
        description: 'A strong tidal canal connecting Mosquito Lagoon to the Indian River Lagoon. Famous for heavy concentrations of redfish on every tide change and migrating tarpon in spring and fall.',
        features: ['canal', 'tidal-current', 'bridge', 'structure'],
        tidePreference: 'outgoing',
        tips: [
            'Fish bridge pilings on outgoing tide — snook and reds lock in the current breaks',
            'Large tarpon migrate through spring and fall; live mullet or big swimbaits work',
            'The current rip at the canal mouth is prime redfish territory',
            'Jig-and-shrimp combos are deadly in the current',
        ],
    },
    {
        id: 'nasa-causeway',
        name: 'NASA Causeway (SR-405)',
        lat: 28.6004,
        lng: -80.7078,
        species: ['tarpon', 'snook', 'redfish'],
        description: 'The bridge spanning the Indian River near the Kennedy Space Center. Deep structure and strong tidal flow make this a go-to for all three species, particularly at night under the bridge lights.',
        features: ['bridge', 'deep-water', 'tidal-current', 'night-fishing'],
        tidePreference: 'outgoing',
        tips: [
            'Night fishing under bridge lights is exceptional for trophy snook',
            'Summer tarpon pile up under the span; live threadfin shad are top bait',
            'Fish the downcurrent side of bridge pilings for the best action',
            'Shallow flats on both sides hold redfish on the incoming tide',
        ],
    },
    {
        id: 'titusville-flats',
        name: 'Titusville Indian River Flats',
        lat: 28.580,
        lng: -80.740,
        species: ['redfish', 'snook'],
        description: 'Expansive seagrass flats stretching along the western shore of the Indian River near Titusville. Consistent year-round redfish and snook action with excellent sight-fishing opportunities.',
        features: ['flats', 'grass', 'shallow', 'wade-fishing'],
        tidePreference: 'incoming',
        tips: [
            'Incoming tide pushes fish onto the flats — be there early',
            'Look for nervous water, wakes, or tailing fish',
            'DOA paddle tails and gold spoons are local favorites',
            'Wade fishing is very productive on windless mornings',
        ],
    },
    {
        id: 'port-canaveral',
        name: 'Port Canaveral Inlet',
        lat: 28.4089,
        lng: -80.5967,
        species: ['tarpon', 'snook'],
        description: 'A premier sportfishing inlet with powerful tidal flows that concentrate baitfish and predators. World-class tarpon action from May through August and consistent snook fishing year-round off the jetty rocks.',
        features: ['inlet', 'jetty', 'deep-water', 'ocean-access', 'tidal-current'],
        tidePreference: 'outgoing',
        tips: [
            'Tarpon school in the inlet May–August, peaking near new and full moons',
            'Live pilchards, threadfin shad, and large swimbaits are top producers',
            'Snook stack on the outgoing tide around the jetty rocks',
            'Watch for the color change where cleaner ocean water meets lagoon water',
        ],
    },
    {
        id: 'canaveral-bight',
        name: 'Canaveral Bight',
        lat: 28.420,
        lng: -80.620,
        species: ['redfish', 'snook'],
        description: 'Protected waters inside Cape Canaveral with extensive oyster bars, scattered grass flats, and minimal boat traffic. Excellent wade fishing and kayak destination with good numbers of both redfish and snook.',
        features: ['flats', 'oyster-bars', 'protected', 'kayak-friendly'],
        tidePreference: 'incoming',
        tips: [
            'Oyster bars are prime ambush points for snook and redfish year-round',
            'Wade fishing is extremely effective in this area',
            'Small topwater plugs at dawn produce explosive strikes',
            'Protected from north and northwest winds — fish here on breezy days',
        ],
    },
    {
        id: 'banana-river',
        name: 'Banana River Flats (Cocoa)',
        lat: 28.350,
        lng: -80.670,
        species: ['snook', 'tarpon', 'redfish'],
        description: 'The Banana River holds productive grass flats, and portions are designated No-Motor Zones, keeping them pristine. Schools of snook and redfish are abundant, and juvenile tarpon frequent the area in summer.',
        features: ['flats', 'grass', 'no-motor-zone', 'kayak-friendly'],
        tidePreference: 'incoming',
        tips: [
            'No-Motor Zones require kayak or push-pole — worth every paddle stroke',
            'Snook and reds are abundant with minimal fishing pressure',
            'Juvenile tarpon frequently roll on the surface in warmer months',
            'DOA paddle tails and MirrOlures are local staples',
        ],
    },
    {
        id: 'sykes-creek',
        name: 'Sykes Creek',
        lat: 28.360,
        lng: -80.680,
        species: ['snook', 'redfish'],
        description: 'A productive tidal creek with good mangrove habitat near Merritt Island. Resident snook and redfish year-round, with excellent current action on outgoing tides.',
        features: ['creek', 'mangroves', 'structure', 'sheltered'],
        tidePreference: 'outgoing',
        tips: [
            'Cast tight to mangrove roots and let your lure sink in the shadow',
            'Small paddle tail jigs and DOA shrimp work great in the current',
            'Best on outgoing tide as fish set up in the current seams',
            'Sheltered from wind — a good option when the lagoon is choppy',
        ],
    },
    {
        id: 'eau-gallie',
        name: 'Eau Gallie River Mouth',
        lat: 28.145,
        lng: -80.625,
        species: ['snook', 'tarpon'],
        description: 'Where the Eau Gallie River meets the Indian River Lagoon. Dock structure, strong tidal flow, and bridge lights make this a reliable spot for trophy snook and seasonal tarpon.',
        features: ['river-mouth', 'docks', 'tidal-current', 'night-fishing'],
        tidePreference: 'outgoing',
        tips: [
            'Dock lights concentrate snook at night — work the shadow lines',
            'Tarpon show up in summer chasing mullet near the river mouth',
            'Live croakers and pinfish are top natural baits',
            'Artificial shrimp under a popping cork is deadly on the outgoing',
        ],
    },
    {
        id: 'melbourne-causeway',
        name: 'Melbourne Causeway (US-192)',
        lat: 28.085,
        lng: -80.607,
        species: ['snook', 'tarpon'],
        description: 'Classic Florida bridge fishing at its finest. The US-192 causeway spans the Indian River at Melbourne with powerful lights that attract baitfish — and the snook that crush them — throughout the night.',
        features: ['bridge', 'bridge-lights', 'structure', 'night-fishing'],
        tidePreference: 'outgoing',
        tips: [
            'Night fishing under bridge lights is legendary — arrive before dark',
            'Position downcurrent of the pilings and work the shadow edge',
            'Tarpon roll through during warmer months, especially June–September',
            'Live shrimp, mullet, or DOA Shrimp paddle tails are classic choices',
        ],
    },
    {
        id: 'dragon-point',
        name: 'Dragon Point',
        lat: 28.097,
        lng: -80.577,
        species: ['snook', 'redfish'],
        description: 'A prominent point on the Indian River south of Melbourne with rocky bottom and scattered oyster bars. The point creates a current seam that concentrates fish on falling tides.',
        features: ['point', 'rock-structure', 'oyster-bars', 'current-seam'],
        tidePreference: 'outgoing',
        tips: [
            'The point funnels current and bait — fish it hard on outgoing tide',
            'Rocky structure holds snook that are tough to pull off the bottom',
            'Redfish work the oyster bar edges on both tides',
            'Swimbaits and jerkbaits are highly effective here',
        ],
    },
    {
        id: 'turkey-creek',
        name: 'Turkey Creek (Palm Bay)',
        lat: 28.027,
        lng: -80.668,
        species: ['snook', 'redfish'],
        description: 'A scenic, tannic tidal creek with excellent mangrove habitat and surprisingly good fishing. Resident snook and redfish year-round, and excellent paddleboard or kayak access.',
        features: ['creek', 'mangroves', 'tannic-water', 'kayak-friendly', 'backcountry'],
        tidePreference: 'outgoing',
        tips: [
            'Work topwater plugs through mangrove pockets at first light',
            'Red-and-white bucktail jigs work year-round in the tea-colored water',
            'Redfish school near the creek mouth on the flats at high tide',
            'Excellent destination for kayak or paddleboard anglers',
        ],
    },
    {
        id: 'mathers-bridge',
        name: "Mather's Bridge (SR-192)",
        lat: 28.092,
        lng: -80.579,
        species: ['snook', 'tarpon', 'redfish'],
        description: 'The old US-192 bridge near Melbourne offers structure, lights, and strong tidal flow. A consistent night-fishing destination for snook, with tarpon appearances from spring through fall.',
        features: ['bridge', 'bridge-lights', 'structure', 'night-fishing'],
        tidePreference: 'outgoing',
        tips: [
            'Night fishing is exceptional from spring through fall',
            'Trophy snook hold in the shadows at the bridge light edges',
            'Artificial shrimp on a 1/8 oz jig head under the lights',
            'Tarpon can appear any time from May through September',
        ],
    },
    {
        id: 'sebastian-inlet',
        name: 'Sebastian Inlet',
        lat: 27.8669,
        lng: -80.4494,
        species: ['tarpon', 'snook'],
        description: 'A bucket-list Florida fishing destination on the southern border of Brevard County. Sebastian Inlet is world-famous for monster snook off the First Point jetty and massive tarpon runs — one of the top snook fisheries on the entire Atlantic coast.',
        features: ['inlet', 'jetty', 'deep-water', 'strong-current', 'world-class'],
        tidePreference: 'outgoing',
        tips: [
            'The First Point jetty is globally renowned for trophy snook — 20–40+ lb fish are common',
            'Tarpon up to 150+ lbs pour through the inlet May–August',
            'Outgoing tide is king — baitfish pouring out of the lagoon triggers explosive feeding',
            'Live mullet, pilchards, and large jigs are the proven approaches',
            'Please practice catch-and-release — these fish are irreplaceable',
        ],
    },
];
